import assert from 'node:assert/strict';
import {MaterialLibrary} from '../web/material.mjs';
import {validateQuestions,validateState,emptyState,newSession,allQuestions,questionKey} from '../web/core.mjs';
const essay=validateQuestions([{id:'e',examId:'gken',type:'essay',prompt:'論述',evaluationGuide:'出題趣旨と自己評価基準',source:'テスト'}])[0];
assert.equal(essay.modelAnswer,'');assert.equal(essay.evaluationGuide,'出題趣旨と自己評価基準');
assert.throws(()=>validateQuestions([{...essay,evaluationGuide:''}]),/模範解答/);
const q=validateQuestions([{id:'q',examId:'sg',type:'single',prompt:'問題',options:['ア','イ'],answer:1,year:'2025',term:'秋期'}])[0];
const index=[{id:q.id,examId:q.examId,type:q.type,options:['0','1'],catalogOnly:true}];
let calls=0;
const library=new MaterialLibrary(index,[{examId:'sg',url:'material/test.json',count:1}],async()=>{calls++;return Response.json([q]);});
const state=emptyState();state.selectedExam='sg';state.session=newSession([q],1,'再開');state.session.pending=1;
assert.equal(validateState(state,library.base).session.pending,1);
await Promise.all([library.load('sg'),library.load('sg')]);assert.equal(calls,1);assert.equal(library.base[0].prompt,'問題');
await library.load('sg');assert.equal(calls,1);
assert.equal(allQuestions(library.base,{custom:[{...q,prompt:'利用者の編集'}]})[0].prompt,'利用者の編集');
const failed=new MaterialLibrary(index,[{examId:'sg',url:'x',count:1}],async()=>Response.json([{...q,id:'wrong'}]));
await assert.rejects(failed.load('sg'));assert.equal(failed.base[0].catalogOnly,true);assert.equal(failed.loaded.size,0);
failed.request=async()=>Response.json([q]);await failed.load('sg');assert.equal(failed.loaded.has('sg'),true);
assert.equal(questionKey(q),'sg::q');
console.log('PASS: private material loading, retry, deduplicated requests, index validation, old state and user edits, essay guidance');
