import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {loadCorrections,applyTextCorrection,applyQuestionImageText,applySolutionText,applyReviewedImages,applySupplementaryImageText,sha,fieldStatus} from '../scripts/material-transcription.mjs';
import {validateQuestions,emptyState,newSession,record,validateState,correctAnswer} from '../web/core.mjs';
import {richText} from '../web/render.mjs';
import {compactQuestionPack} from '../scripts/library-catalog.mjs';

const read=file=>JSON.parse(readFileSync(file));
const corrections=loadCorrections();assert.ok(corrections.size>=10);
const supplementaryQuestion=validateQuestions([{id:'supplement',examId:'fixture',prompt:'Read the image.',options:['A','B'],answer:0,images:[{src:'assets/question.png',alt:'Question'}],solutionImages:[{src:'assets/solution.png',alt:'Solution'}]}])[0];
const candidate=text=>({status:'unreviewed',method:'ocr',text,textSha256:sha(text)});
const candidates={'assets/question.png':candidate('Question 0.02 kg'), 'assets/solution.png':candidate('Answer B: because 0.02 kg')};
const supplemented=applySupplementaryImageText(supplementaryQuestion,candidates).question;
assert.ok(supplemented.passage.includes('Question 0.02 kg') && supplemented.explanation.includes('Answer B'));
assert.deepEqual(supplemented.images,supplementaryQuestion.images);assert.deepEqual(supplemented.solutionImages,supplementaryQuestion.solutionImages);
assert.equal(supplemented.answer,0);assert.deepEqual(supplemented.options,supplementaryQuestion.options);
assert.deepEqual(applySupplementaryImageText(supplemented,candidates).question,supplemented);
assert.equal(applySupplementaryImageText({...supplementaryQuestion,textReview:{passage:'source-verified'}},candidates).question.passage,supplementaryQuestion.passage);
assert.throws(()=>applySupplementaryImageText(supplementaryQuestion,{}),/Missing image/);
assert.throws(()=>applySupplementaryImageText(supplementaryQuestion,{'assets/question.png':{...candidates['assets/question.png'],text:'tampered'}}),/Changed extracted/);
assert.equal(applySupplementaryImageText(supplementaryQuestion,{...candidates,'assets/question.png':candidate('x'.repeat(50000))}).pending.length,1);
assert.deepEqual(validateQuestions(compactQuestionPack([supplemented])),[supplemented]);
const croppedCandidates={...candidates,'assets/question.png':{...candidates['assets/question.png'],crops:[{src:'assets/transcription/figure.png'}]}};
const croppedQuestion=applySupplementaryImageText(supplementaryQuestion,croppedCandidates).question;
assert.equal(croppedQuestion.images[0].src,'assets/transcription/figure.png');assert.ok(croppedQuestion.images[0].alt.includes('文字化できない部分'));
assert.deepEqual(croppedQuestion.solutionImages,supplementaryQuestion.solutionImages);
const flattened={...supplementaryQuestion,passage:'Old flattened diagram text'};
const exactSource={...croppedCandidates,'assets/question.png':{...croppedCandidates['assets/question.png'],sourceText:flattened.passage}};
assert.ok(!applySupplementaryImageText(flattened,exactSource).question.passage.includes('Old flattened'));
assert.ok(applySupplementaryImageText({...flattened,passage:'Unrelated source instructions'},exactSource).question.passage.includes('Unrelated source instructions'));
const imageAnswer={type:'written',modelAnswer:'Existing verified answer.',textReview:{modelAnswer:'source-verified'},solutionImages:[{src:'assets/text.png'},{src:'assets/diagram.png'}]};
const solution={field:'modelAnswer',text:'Source answer: 0.02 kg, not 002 kg.',removed:[{image:imageAnswer.solutionImages[0]}],retained:[imageAnswer.solutionImages[1]]};
const answerText=applySolutionText(imageAnswer,solution);
assert.ok(answerText.modelAnswer.includes('Existing verified answer.') && answerText.modelAnswer.includes('0.02 kg'));
assert.deepEqual(answerText.solutionImages,[imageAnswer.solutionImages[1]]);assert.equal(answerText.textReview,undefined);
assert.throws(()=>applySolutionText({...imageAnswer,solutionImages:[]},solution),/mapping changed/);
assert.throws(()=>applySolutionText(imageAnswer,{...solution,field:'answer'}));
for(const field of ['explanation','evaluationGuide']) assert.ok(applySolutionText({...imageAnswer,[field]:''},{...solution,field})[field].includes('0.02 kg'));
const reviewedAnswer={...imageAnswer,id:'reviewed',examId:'fixture',modelAnswer:'原本と照合済みの解答例',textReview:{modelAnswer:'source-verified'}};
const reviewedCorrection={key:'fixture::reviewed',after:{textReview:{modelAnswer:'source-verified'}}};
const preservedAnswer=applySolutionText(reviewedAnswer,solution,reviewedCorrection);
assert.equal(preservedAnswer.modelAnswer,reviewedAnswer.modelAnswer);assert.deepEqual(preservedAnswer.textReview,reviewedAnswer.textReview);
assert.deepEqual(preservedAnswer.solutionImages,solution.retained);
const questionImage={id:'q',examId:'fixture',prompt:'Read both sources.',passage:'',options:[],images:imageAnswer.solutionImages};
const questionPart={text:solution.text,sourceText:solution.text,removed:solution.removed,retained:solution.retained};
const partialQuestion=applyQuestionImageText(questionImage,questionPart);
assert.ok(partialQuestion.prompt.includes('0.02 kg'));assert.deepEqual(partialQuestion.images,questionPart.retained);
assert.throws(()=>applyQuestionImageText({...questionImage,images:[]},questionPart),/mapping changed/);
const completeQuestion=applyQuestionImageText({...questionImage,images:[questionImage.images[0]]},{...questionPart,retained:[]});
assert.equal(completeQuestion.passage,solution.text);assert.deepEqual(completeQuestion.images,[]);
const source='build/private/web/material/';
const nw=validateQuestions(read(source+'archive-2009h21a_nw_am2.json'))[0],fixed=applyTextCorrection(nw,corrections);
assert.deepEqual(fixed.options,['ア　0.02','イ　0.08','ウ　0.16','エ　1.6']);
assert.ok(fixed.prompt.includes('1,000バイト') && fixed.prompt.includes('50％'));
assert.equal(correctAnswer(fixed,2),true);assert.deepEqual(fixed.images,nw.images);
assert.deepEqual(applyReviewedImages(fixed,corrections).images,[]);
const reviewedImage=corrections.get(nw.examId+'::'+nw.id).imageReplacement.images[0];
const derived={...fixed,images:[{src:'assets/compact/reviewed.webp'}]};
assert.deepEqual(applyReviewedImages(derived,corrections,{[reviewedImage.src]:{src:derived.images[0].src,sourceSha256:reviewedImage.sha256}}).images,[]);
assert.throws(()=>applyReviewedImages(derived,corrections,{[reviewedImage.src]:{src:derived.images[0].src,sourceSha256:'changed'}}),/mapping changed/);
assert.deepEqual(applyTextCorrection(fixed,corrections),fixed,'Reapplying a correction is idempotent');
assert.throws(()=>applyTextCorrection({...nw,prompt:'Changed by another importer'},corrections),/Stale correction/);
const state=emptyState();state.selectedExam='nw';state.session=newSession([nw],1,'existing session');record(state,nw,2,1);
assert.deepEqual(validateState(state,[nw]),validateState(state,[fixed]),'Old learning records and choice mapping survive');
const fe=validateQuestions(read(source+'archive-2023r05_fe_kamoku_a.json'));
const table=applyTextCorrection(fe[1],corrections);
assert.ok(table.passage.includes('| 200 | 社員T | 0 | 300 |'));
assert.equal((richText(table.passage).match(/<table>/g) || []).length,2);
assert.equal(fieldStatus(table,'explanation'),'absent-in-source');
assert.equal(fieldStatus({...table,explanationKind:undefined,textReview:undefined},'explanation'),'empty-availability-unknown');
const code=applyTextCorrection(validateQuestions(read(source+'archive-2023r05_fe_kamoku_b.json'))[0],corrections);
assert.ok(code.prompt.includes('［a］と［b］'));assert.ok(code.passage.includes('      if (［b］)\n          divideFlag ← false'));
assert.ok(code.options[1].includes('1 と等しくない'));assert.ok(richText(code.passage).includes('<code>'));
for(const q of validateQuestions(read(source+'archive-2023r05_fe_kamoku_b.json'))) {
  const fixed=applyTextCorrection(q,corrections);
  assert.ok(fixed.passage.includes('演算子 mod は，剰余算を表す。') && fixed.passage.includes('1行分の内容を表す。'));
  assert.deepEqual(fixed.answer,q.answer);
}
const formula=applyTextCorrection(validateQuestions(read(source+'2023r05a_ap_am-ap.json'))[0],corrections);
assert.ok(formula.prompt.includes('x₁x₂') && formula.prompt.includes('x₂x₁'));assert.equal(formula.options[2],'ウ　2x−3 int(x/2)');assert.ok(formula.images.length);
const st=validateQuestions(read(source+'2023r05h_st_pm1-st.json')).slice(0,4).map(q=>applyTextCorrection(q,corrections));
assert.equal(st[0].answerKind,'answer-example');assert.equal(st[0].explanationKind,'grading-commentary');
assert.ok(st[0].evaluationGuide.includes('能力を評価する'));assert.ok(!st[0].modelAnswer.includes('能力を評価する'));
assert.ok(st[0].passage.includes('暗号資産') && st[0].passage.includes('顧客体験価値（UX）'));
assert.ok(st[0].passage.includes('40字以内') && st[0].passage.includes('30字以内'));assert.ok(!/49字|39字/.test(st[0].passage));
assert.ok(st[0].passage.includes('［下線①：'));assert.ok(st[0].passage.includes('ウォレット機能'));assert.equal(st[0].images.length,4);
assert.deepEqual(validateQuestions(compactQuestionPack(st)),st,'Shared corrected multi-page text roundtrips');
assert.deepEqual(validateQuestions([fixed])[0],fixed);
assert.throws(()=>validateQuestions([{...fixed,textReview:{passage:'ocr-high-confidence'}}]),/文字照合/);
assert.throws(()=>validateQuestions([{...fixed,explanationKind:'model-answer'}]),/種別/);
assert.equal(fieldStatus({...nw,images:[]},'options'),fieldStatus(nw,'options'),'Image count is not text completeness');
const folder=mkdtempSync(join(tmpdir(),'transcription-check-'));
try {
  const path=join(folder,'corrections.json'),r=structuredClone([...corrections.values()][0]);
  r.status='unreviewed';writeFileSync(path,JSON.stringify([r]));assert.throws(()=>loadCorrections(path),/Unreviewed/);
  r.status='source-verified';r.evidence[0].sha256='wrong';writeFileSync(path,JSON.stringify([r]));assert.throws(()=>loadCorrections(path),/Source changed/);
  r.evidence[0].sha256=[...corrections.values()][0].evidence[0].sha256;r.after.answer=0;r.before.answer=[2];writeFileSync(path,JSON.stringify([r]));assert.throws(()=>loadCorrections(path),/Forbidden correction field/);
} finally {rmSync(folder,{recursive:true,force:true});}
console.log('PASS: decimal/unit/negation/box/subscript/table/code/multi-page/source-kind regressions, stale/hash/unreviewed rejection, saved state and compact roundtrip');
